
server:
  port: 8888
spring:
  thymeleaf:
    mode: HTML5

# 修改默认的静态寻址资源目录
#spring.resources.static-locations = classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/     #注册中心地址
#spring:
#  application:
#    name: province-server